jdbc:
  username: cmrhyq
  password: Hyq0901.
  jdbcUrl: jdbc:mysql://bj.kevinkda.cn:3306/HuangSir
  driverClassName: com.mysql.cj.jdbc.Driver
#
Server:
  port: 6666
  servlet:
    context-path:  /ssm