jdbc:
  username: root
  password: admin
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  driverClassName: com.mysql.jdbc.Driver


#server:
#  port: 6666
#  servlet:
#    context-path: /ssm
